### ISSUE TITLE
Audio Example Does Nothing?

### ISSUE THREAD

**Issue by AtomicPerception** [toadstorm/MOPS#121]
I have supplied a stereo MP3 file to the Audio example but I don't get an motion/animation when I play the timeline. I do hear the wave file playing, however. I tried tweaking the various channel frequency ranges by extending the high end up to 20,000hz but I still get no action.

Is there something more to activating the animation other than choosing a sound file?

**Comment by AtomicPerception** [comment]
Ok, it does look like a bad default is in place. Under the SHIFT tab you may want to set the Start parameter to 0 instead of -20. Once I set this to zero I begin to see some action.

**Comment by toadstorm** [comment]
Yeah, the shift that was in there was for a particular audio track... not sure why it works for that track and not others, unless the track is less than 20 seconds long. Certain MP3's seem to load more reliably than others, and some even seem to be truncated and I'm not sure if this is a Houdini problem or a MOPs problem. Either way, that's specifically for the example file (since many tracks don't start right away), but it's not technically a default... if you drop down a new Audio Falloff, the offset is 0.
