### ISSUE TITLE
MOPs Parallel Transport - Biased orientation

### ISSUE THREAD

**Issue by profbetis** [toadstorm/MOPS#145]
When using the MOPs Instancer along a curve, instances are oriented only according to the point ahead of them and not an average of in front and behind to give a smoother and unbiased direction.

I've traced this back to the Parallel Transport node. When initializing the arrays, the tangents are calculated by the difference between the position of the current and next point. To fix this, I suggest averaging the difference between the next point and the previous point.

This is how I implemented the change:
```c
// fill arrays
for (int i = 0; i<pntcnt-1; i++)
{
    vector thispos = point(geoself(), "P", pnts[i]);
    vector prevpos = point(geoself(), "P", pnts[i-1]);
    vector nextpos = point(geoself(), "P", pnts[i+1]);
    push(tangents, normalize(normalize(nextpos - thispos) + normalize(thispos - prevpos)));
    push(normals, firstnormal);
}

**Comment by profbetis** [comment]
Here's a paste of the whole node's snippet which includes some edits to the main body to be less biased, but it didn't seem to have an effect and is untested: https://pastebin.com/nxHSzCYM

**Comment by toadstorm** [comment]
The proposed change makes sense in some situations, but not others. When running on closed loops, blending the orientations between neighboring points causes flipping at the closure point. See this example file: https://drive.google.com/file/d/1GeYhEF4dxgr8DnlWfsF6yz4P_d3t_iSO/view?usp=sharing

If you apply your code patch to the MOPs Parallel Transport wrangle, you'll see the tangents go haywire at the closure point.

I suppose we could add a separate "mode" to parallel transport in order to allow for the kind of biasing you're using here, but I wonder if there's a better way to handle this.
