### ISSUE TITLE
Dsitribute Curve issue with Randomize Modifier

### ISSUE THREAD

**Issue by sepux** [toadstorm/MOPS#151]
In distribute type "Curve" mode if you slice the curve an animate any of the slice options and add a randomize modifier (Maybe with other modifier happens as well) it gets all fucked up. 

Also, I added a note, let me know if it is possible to add functionality for the instance to be growing randomly like the curves that I have there in green. Thanks!

![2019-01-11_23-51-41](https://user-images.githubusercontent.com/20706047/51070936-7593ae80-15fe-11e9-95b4-3d1a7f4ede80.gif)

[MOPs_Issue_v02.zip](https://github.com/toadstorm/MOPS/files/2751817/MOPs_Issue_v02.zip)

**Comment by toadstorm** [comment]
The issue here is that the i@id attribute of the instances isn't stable because of the animated carve happening... the tips of the carved curves always have an id of -1, and on top of that it scrambles the point order.

This is something that'll have to be worked out, but it might take a minute to figure how how to generate stable IDs for the animated carve, the tips, and the generated instances, so that they all match as expected. In the meantime I'd recommend against animating the carve; instead, maybe generate all the clones up front and then blast them afterwards.

**Comment by toadstorm** [comment]
Revisiting this again, this seems to work fine as long as you're carving starting from the endpoint instead of the beginning. To make this a bit more obvious a choice, I'm switching the defaults for the Carve options to enable Second U and disable First U by default. This will be implemented in 0.1.51 Experimental.
