### ISSUE TITLE
MOPS Spring Modifier issue

### ISSUE THREAD

**Issue by fakepilot** [toadstorm/MOPS#185]
When I use the Spring modifier, I loose all my geometry until I have checked and unchecked "Preview Falloff". Have to do this every time I make a change. Last version I tried this was MOPS-0.1.51e.

**Comment by toadstorm** [comment]
The Spring modifier is a Solver SOP internally, and as far as I know this problem is endemic to the Solver SOP. Hitting the "Reset Simulation" button on the Spring Modifier's "Solver" tab typically also resolves the problem. I'm honestly not sure if there's a better way to force Houdini to know to recompute a solver, but I'm open to suggestions!

**Comment by fakepilot** [comment]
I found this page:
[nicholaspfeiffer.com/blog/...](http://nicholaspfeiffer.com/blog/2016/2/20/houdini-tip-of-the-day-python-pressbutton-and-set-commands)
There is two Python commands, that can be added to a shelf tool and a hotkey, or in a wrangle etc.
```
hou.parm('/obj/sphere_object1/rop_alembic1/execute').pressButton()
hou.parm('/obj/AutoDopNetwork/isplayer').set(1)
```
They can be used to target and click a button, like the Reset Simulation button.
Not sure exactly, how this could be done by auto in MOPs. 

I used it myself on the Reload button on a File node, to update an EPS file with a hotkey.

Maybe it helps? Good suggestion? :-)

**Comment by toadstorm** [comment]
Yeah, .pressButton() could be run via Python to reset the simulation, but the problem is knowing exactly when to reset the simulation. I'm not sure I know of an easy way to guess when the sim needs to be reset in this way.

I could add a shelf tool to automatically reset all simulations in the current SOP network? This is a pretty standard problem to have with Solvers in Houdini.

**Comment by fakepilot** [comment]
Maybe a reset and play from start button. Or reset, cache and play from start.

On a side note, sorry for putting this in the wrong place...
I just came up with a way to get a live connection with Affinity Designer and Houdini.
With the Export persona, you can set Designer up to export an EPS (and convert text curves) continuosly.
So whenever you make a change to your Affinity document, it exports an EPS and overwrites without needing to click save. With a File node, you load that EPS and with a hotkey with this script, you can update whatever you have loaded in. A future feature of MOPs should be a node to convert this EPS or SVG to an extruded and beveled and normaled MOPs object. Maybe even loads it by auto, when the file changes. Only caviat with Houdini loading EPS is that holes become objects with the normal in the opposite direction, I'm sure you know. Can easily be extruded and boolean'ed, but doing this by auto - would be king. Also not sure if it's possible to get in colors. With SVG this should be possible...
