### ISSUE TITLE
MOPs Parallel Transport not outputting normals & binormals

### ISSUE THREAD

**Issue by charlesnyiha** [toadstorm/MOPS#224]
Hello,
The MOPs Parallel Transport node doesn't seem to output normals and binormals, only tangents.
I'm not very experienced at programming, so it might be just me but I've tried testing it and the same results always appear. I've attached some JPEGs where I compare it to the Polyframe node with the same input spline, which works okay.

It still doesn't work even when I select the 'Custom First Tangent' checkbox.
And I'm using MOPS-0.1.71e.

![ptbug_01](https://user-images.githubusercontent.com/54474398/68736812-c6937b00-05f2-11ea-9676-fbe5839ba0c7.jpg)
![ptbug_02](https://user-images.githubusercontent.com/54474398/68737045-5f29fb00-05f3-11ea-9abf-5ba6d384e375.jpg)
![ptbug_03](https://user-images.githubusercontent.com/54474398/68736821-cbf0c580-05f2-11ea-98d6-404228a2c66c.jpg)
![ptbug_04](https://user-images.githubusercontent.com/54474398/68736824-cdba8900-05f2-11ea-8941-573511bc9faa.jpg)

**Comment by toadstorm** [comment]
Nice catch! That operation doesn't seem to work if the curve doesn't have an N attribute... MOPs Orient Curve automatically computes N before running parallel transport, which is why I guess I left this unnoticed. I just patched it in the `henry_dev` branch if you want to try it, or just compute N beforehand and you should get the right values.

**Comment by charlesnyiha** [comment]
Thanks!
