### ISSUE TITLE
Lastest 17.5 compatible version ?

### ISSUE THREAD

**Issue by melMass** [toadstorm/MOPS#260]
It took me two years to get into it, but since the HIVE presentation, I have used MOPS almost daily.
I was wondering if there is a specific tag or commit when the compatibility with H17.5 was broke?

Some nodes have warnings and errors, and others seem to crash Houdini

Thanks a lot

**Comment by toadstorm** [comment]
Can you please be more specific about the warnings, errors and crashes
you're encountering?

The latest Experimental build has some issues with warnings, but there
should be no crashes. A more descriptive bug report, including HIP files if
possible, would be really helpful in debugging the problem.

**Comment by melMass** [comment]
The example `animated instance.hip` for instance is not working (both outputs are synced not offset, no warning). I'm trying to use an alembic sequence and delay it using mops.

It seems like the `Move Along Spline` nodes is giving an error when I reopen a file containing it:
![image](https://user-images.githubusercontent.com/7041726/85239687-2c6f9d00-b435-11ea-8b34-80d1a20659f7.png)
![image](https://user-images.githubusercontent.com/7041726/85239699-47daa800-b435-11ea-8e50-2836c76c1192.png)

**Comment by toadstorm** [comment]
For the animated_instances example file, you need to go back to /obj/simple_animation and cache the sequence first. The Instancer in /obj/instances is currently set to load the Alembic file, so cache /obj/simple_animation/rop_alembic1. Then you should be able to read the sequence in /obj/instances. If you don't see the time offset, try putting the display flag on the Unpack SOP... packed nodes don't always display well in the viewport when animating.

Regarding the other warnings... these are appearing because there are some new attributes in Houdini 18 that don't exist in 17.5. Most of those errors you're seeing are specific to a "VEX Precision" attribute on the many Attribute Wrangle nodes throughout MOPs. These warnings are annoying, but they shouldn't prevent MOPs from actually working.

If you run into any repeatable crashes from MOPs nodes, please provide a HIP file and instructions on how to recreate the crash if at all possible.

**Comment by melMass** [comment]
Well after reading each of them they are all skipped without error so unless you use those parms it's not the issue..

--- Just received your answer

Thanks, yes I did cache both and I just tried to unpack put it does not work on my end:

![mops_instances](https://user-images.githubusercontent.com/7041726/85240485-a9e8dc80-b438-11ea-83c3-8cce417eefaf.gif)

But as I thought the library was not H17.5 compliant, I might not use the latest version, let me remedy to that right now.

**Comment by toadstorm** [comment]
That doesn't look like you unpacked anything at all, unless I'm misreading your GIF there. Try appending an Unpack SOP **after** either the MOPs Delay or the MOPs Set Sequence Time nodes.

**Comment by melMass** [comment]
@toadstorm Yes sorry I did the unpack but it was too slow for a GIF so I edited it out.

**Comment by toadstorm** [comment]
The example file works fine here. Try updating MOPs to the latest Experimental build. If it still doesn't work, please submit a HIP file.

**Comment by melMass** [comment]
Here is a simple test on a move_along_spline, the sequence is supposed to pass through no?
![mops_instances-2](https://user-images.githubusercontent.com/7041726/85241177-3c8a7b00-b43b-11ea-8d09-baa3bda6ff92.gif)

**Comment by melMass** [comment]
The `MOPS Set Sequence Time` nodes used in the sample now works! 
The Delay does not look bulgy and buggy anymore, but no animation is playing, I will be able to work out my issue with the Set Sequence Time.
When I have more time I'll do a deeper test

**Comment by melMass** [comment]
Ok using the MOPS Instancer instead of an Alembic node is solving the time offset issue. 
The Move Along Spline still freezes, but now instead of the first frame, it's another one.

**Comment by toadstorm** [comment]
The Move Along Spline issue is because Move Along Spline by default has a constant "Attach Time" that effectively freezes your geometry so that its movement doesn't interfere with the attachment settings (where MOPs decides what the "starting" transformation of each instance is). There's two things you can do here: you can just set your sequence time *after* the Move Along Spline operation, or you can change the "Attach Time" to `@Frame` instead of the default `$FSTART`. This could end up with weird results if your instances were actually moving in space before the Move Along Spline operation, which is why it defaults to $FSTART.

**Comment by toadstorm** [comment]
Regarding the time offset differences between the Alembic SOP and the MOPs Instancer... Set Sequence Time, Delay, and similar nodes in MOPs only know how to cycle the timing of Alembics by way of special attributes that are assigned by either the MOPs Instancer, or by MOPs Set Sequence Time if "Set Cycling Mode" and "Set Alembic Range" are enabled. Otherwise, Houdini by default doesn't cycle Alembic animations. I recommend reading the help card built into MOPs Set Sequence Time for more information on this.

**Comment by melMass** [comment]
Perfect thanks that was it, it all works, but I think I have a similar issue to what you were referring to. It seems like the Transform Modifier is recalculating based on BBox? Look at the end, the shrinking of all the flowers come from the Transform Modifier (the falloff is not modified at this point, that's why I think BBox):

![mops_instances-3](https://user-images.githubusercontent.com/7041726/85246647-7d8a8b80-b44b-11ea-92d0-2819301acb8e.gif)

**Comment by toadstorm** [comment]
No, the Transform Modifier doesn't care about your bounding box at all. If I had to guess, I'd say the pivot point of your original geometry being instanced is changing over time? Maybe it's not always at the origin, or you have it packing at the centroid?

I'm going to close this issue because the original problem was resolved. If you can't figure out this latest pivots issue you just mentioned, feel free to ask for help on the MOPs Forum, in the MOPs Users Group on Facebook, or email me directly with the HIP file included. If you think you've found another bug, please open a new issue here.

**Comment by melMass** [comment]
Yes, that must be the issue good call!
Thanks a lot, MOPs just saved me.
