### ISSUE TITLE
MOPS Instancer: Template Group parameter not working properly for Curve Distribution mode

### ISSUE THREAD

**Issue by charlesnyiha** [toadstorm/MOPS#270]
Hello,

I think there's a problem with the MOPs Instancer in Curve Distribution mode. I'm trying to copy objects onto specific points on curves, but the group parameter isn't working as expected, even when I turn resampling off. The group parameter seems to only accept primitive groups, and not point groups.
I've attached a hip file, if you're interested.

[mops instancer curve grp bug.zip](https://github.com/toadstorm/MOPS/files/5144854/mops.instancer.curve.grp.bug.zip)

**Comment by charlesnyiha** [comment]
Using MOPs v1.2 on Houdini 18.0.460

**Comment by toadstorm** [comment]
Hey Charles,

The group you're trying to create using that Attribute Expression SOP isn't actually being created. There's no expression provided, so the `start` group doesn't exist. You can verify this with MMB. If you change the Expression parameter to `1` it should work as expected.

**Comment by charlesnyiha** [comment]
Oh no! Sorry! I was testing whether it was working on primitive/point groups and I forgot to retype the expression before I sent the file. Here's a corrected version, where the Group Expression SOP has an expression selecting the end point.

So sorry for wasting your time.

[mops instancer curve grp bug 2.zip](https://github.com/toadstorm/MOPS/files/5145951/mops.instancer.curve.grp.bug.2.zip)

**Comment by toadstorm** [comment]
Ah, okay, this makes sense. The issue here is that the "Template Group" is expecting a primitive group. If you change your Distribution Type to "Mesh" and "Template Point Group" to "Start", this will work. I need to add a Template Point Group mask option for Curve mode, and clarify that the Template Group at the top of those options is specifically a primitive group. I'll add this to the next build. Thanks for reporting.

**Comment by charlesnyiha** [comment]
Yeah, after playing around I found the mesh distribution workaround, so that's what I'm using now. Thanks, and you're welcome!
