### ISSUE TITLE
Mops fetch attribute 

### ISSUE THREAD

**Issue by Misk97** [toadstorm/MOPS#335]
Hi, I'm trying to use the shape falloff node as a vellum constraint, and when I'm trying to bring it in inside the solver using Mops fetch attribute, but I didn't have it among the mops nodes at all . also apparently I can't add any mops inside dope network!   
I watched some tut and people have it all! may I know what is the problem???
any help, please!

**Comment by toadstorm** [comment]
The nodes you're referring to are part of MOPs Plus, an add-on to MOPs. You
can read more about it here: https://motionoperators.com/info/mopsplus/

The MOPs Wiki on Github has a node list. Tools that are part of the Plus
add-on are marked as such.

**Comment by Misk97** [comment]
I downloaded Mops+. I tried to use it with Houdini 20, following a tut using the mops Apply attribute node, but it didn't seem it's working. I'll attach my hip file so you can check if I did any wrong or it's just not compatible with houdini 20 yet !
thanks for the support.
[https://drive.google.com/file/d/1r5a_hoXy7YxJ0WHAjL2RBUSDp4B18bax/view?usp=sharing](url)

**Comment by toadstorm** [comment]
The reason you're not getting the effect you're expecting is because you forgot to configure the Inputs tab of MOPs+ Apply Attributes. The Target Geometry was set to "Second Context Geometry", meaning it was trying to use your Vellum constraint primitives as a target instead of the head geometry. Set the Target Geometry to SOP and point the SOP Path to your animated geometry and it will work.

**Comment by toadstorm** [comment]
Did this resolve the issue?
