### ISSUE TITLE
Submitting Pull Requests

### ISSUE THREAD

**Issue by crydalch** [toadstorm/MOPS#95]
How do you want to receive pull requests? Is there a particular dev branch we should be working from, or just branch from master?

Thanks!

**Comment by toadstorm** [comment]
hey sorry i didn't respond to this sooner! i disabled notifications by accident.

because we can't automatically merge branches with binary files very easily, you can make your own branch and submit a request from that. i have to actually download and copy things over to verify, then I'll merge it. I'm still not a Git expert and with binaries I'm not sure there's an easier way. Thanks!
